### ISSUE TITLE
UnExpect Sql Format Result

### ISSUE THREAD

**Issue by kira8565** [mysqljs/sqlstring#1]
Hi~I use this node-modules for my project ,I want to  format SQL like this 
    
    use itop;
    SELECT a.first_name,b.first_name AS b FROM person AS a LEFT JOIN person AS b ON a.id=b.id 

After I Use the SqlString Format it ,I get the Result like this:

    use itop;SELECT a.first_name,
             b.first_name AS b
    FROM person AS a
    LEFT JOIN person AS b
        ON a.id=b.id 

But Not Like This

    use itop;
    SELECT a.first_name,
             b.first_name AS b
    FROM person AS a
    LEFT JOIN person AS b
        ON a.id=b.id

**Comment by dougwilson** [comment]
As far as I can tell, you are referring to changes in line breaks. This format doesn't touch line breaks, so if you can provide example code that has this issue, that would help a lot!
