### ISSUE TITLE
Handling Arrays in a JSON

### ISSUE THREAD

**Issue by abhgangwar** [mysqljs/sqlstring#14]
Hi,
MySql supports JSON data type: https://dev.mysql.com/doc/refman/5.7/en/json.html .

## Use Case
I want to run an update command on my db with the following data:
`var post = { a: 1,  b: [2, 3, 4], c:  5}`
where the column `b` has JSON data type.
## Actual Behavior
`var sql = "UPDATE tb SET " + SqlString.escape(post) + " WHERE id= " + SqlString.escape(242);`
The formatted query would be
`UPDATE tb SET `a` = 1, `b` = 2, 3, 4, `c` = 5 WHERE id= 242 `
This command would fail.
## Expected Behavior
I want to store JSON data in column `b`. So, the query should be formatted as:
`UPDATE tb SET `a` = 1, `b` = '[2, 3, 4]', `c` = 5 WHERE id= 242 `

**Comment by dougwilson** [comment]
I don't think it is possible to implement that. Do you think it is possible? Would you be willing to make a PR if so?

**Comment by abhgangwar** [comment]
Hi,
I thought of the following idea. Please suggest.
Considering that json key-value pairs are converted as  `key = value`, I'm assuming that the `key` is representing a column name and `value` is representing the data for that column. ( Correct me if I'm wrong ).

## Idea
So, consider the call `escape(abc)` :
If `abc` is a json, then we need all of its key-value pairs to be like `key=value`. We can do the following:
`escapeId(key) + ' = ' + escape(JSON.stringify(val));` .
That way the json data for a column isn't affected. Although I'm not sure what can negatives effects of this. So, please suggest. If the idea is correct, I'll make a pull request.

**Comment by dougwilson** [comment]
That will not work with how the module is written, unfortunately.
