### ISSUE TITLE
Bring up-to-date with mysql@2.11.0

### ISSUE THREAD

**Issue by dougwilson** [mysqljs/sqlstring#2]
We should get this module up-to-date with the new msyql coming up soon, get this module used in there, and start proceeding forward from there.

Hey @fengmk2, do you mind if I take this on, or do you want to? We also would want to support Node.js 0.6 to get used by MySQL@2.x, and there are probably a bunch of packaging changes I would like to make.

Because of this, I just wanted to get on the same page as you: do you want to keep maintaing this module, or did you intend to just donate it to the `mysqljs` organization to take over (and, do you want to participate in `mysqljs` organization at all)?

**Comment by fengmk2** [comment]
Yes, please make changes as you want to.

Sorry for reply too late.

**Comment by dougwilson** [comment]
Hi @fengmk2, it's no problem, I still appreciate the reply! This just being git changes is easily reversible if you said otherwise :) Nothing has been published to npm yet, but I'm thinking to just publish as 2.0.0 so I don't have to figure out what is actually different between what was here in 2014 and what is from the mysql module today :)

**Comment by fengmk2** [comment]
I take a look at the diff and can't found what is actually different too.
Should publish 2.0.0 to npm for the new start!

Nice to see you everywhere! @dougwilson

**Comment by dougwilson** [comment]
Cool. Published as 2.0.0, then immediately realized I messed up the package, so now 2.0.1. Whoops! :confounded:
