### ISSUE TITLE
Add TypeScript Definitions

### ISSUE THREAD

**Issue by sgtoj** [mysqljs/sqlstring#22]
Add TS Definition 

- [x] Create Definition File
- [x] Add typing location to NPM `package.json` 
- [x] Submit MR from Fork
  - [sgtoj/sqlstring:ts-definition](https://github.com/sgtoj/sqlstring/tree/ts-definition)

**Comment by dougwilson** [comment]
FYI I closed your PR because after changes were requested nothing happened for months. If you ever get time to address them please open a new PR!
