### ISSUE TITLE
Escape : charachter

### ISSUE THREAD

**Issue by crmsoft** [mysqljs/sqlstring#25]
Hi, 

I tried to insert some string in my db using mysqljs, 

String looks like this:  ?/*-:;@!#$$%^&

Expected behavior : '?/*-:;@!#$$%^&'

Result: '?/*-'

Nothing included after ":" in any string input.

**Comment by dougwilson** [comment]
Hi @crmsoft I'm can't reproduce:
```
$ node -pe 'require("sqlstring").escape("?/*-:;@!#$$%^&")'
'?/*-:;@!#$$%^&'
```

Can you provide all the following, please?

1. Version of Node.js you are using.
2. Version of this module you are using.
3. Complete code that reproduces your issue.
4. Instructions for how to run the code.

Thanks!

**Comment by crmsoft** [comment]
My fault, sorry, can be closed.

Thanks

**Comment by dougwilson** [comment]
It's no problem, glad you got it sorted :)
