### ISSUE TITLE
When to use escape VS escapeId?

### ISSUE THREAD

**Issue by MarkHerhold** [mysqljs/sqlstring#27]
How should I know when to use `escape()` vs `escapeId()`?

**Comment by dougwilson** [comment]
You would use escape for values and escapeId for identifiers.

**Comment by MarkHerhold** [comment]
I think that fundamentally makes sense, but I am struggling to differentiate between the two. To me they are slightly ambiguous terms.

**Comment by dougwilson** [comment]
I believe it's the terms used by MySQL in the manual and their syntax trees. What are the terms you are seeing in the MySQL server documentation? I may be able to help translate or figure out if there are different terms that should be used, but just don't have enough information to understand why they don't make sense yet.

**Comment by dougwilson** [comment]
Here is the main doc section regarding the SQL language in MySQL if that helps: https://dev.mysql.com/doc/refman/5.7/en/language-structure.html

**Comment by MarkHerhold** [comment]
Oh, this terminology ties directly to SQL queries! Now it's obvious. I guess I was thinking too much about my application's data and not about what constitutes a SQL query.

Thanks! 👍
