### ISSUE TITLE
Escaping single quote

### ISSUE THREAD

**Issue by rocketspacer** [mysqljs/sqlstring#36]
Currently, `sqlstring.escape("jo'hn")` results in `'jo\\'hn'` which is not the correct escape for single quote, the correct escape for single quote should be 2 single quote next to each other and the correct end result is `'jo''hn'`

**Comment by dougwilson** [comment]
Both are correct. https://dev.mysql.com/doc/refman/8.0/en/string-literals.html

**Comment by rocketspacer** [comment]
@dougwilson Then it should be escaped with 1 slash, not 2 slashes, right?
`'jo\\'hn'` vs `'jo\'hn'`

**Comment by dougwilson** [comment]
It only escapes with one slash. How are you converting the string to see the output? For example if you're using `console.dir(str)`, then node.js is adding that extra `\` in the output format.

**Comment by dougwilson** [comment]
$ node
> console.log(require("sqlstring").escape("jo'hn"))
'jo\'hn'
```

**Comment by rocketspacer** [comment]
You're correct, I tested it on Runkit, https://npm.runkit.com/sqlstring and I was fooled

**Comment by dougwilson** [comment]
Ah, I see what you mean. Looks like they echo it out passing through like `JSON.stringify` or something.
