### ISSUE TITLE
Parameterized Identifiers

### ISSUE THREAD

**Issue by stevehogdahl** [mysqljs/sqlstring#48]
I'm trying to run the following query for dynamic sorting. 

```
SELECT * FROM tenant ORDER BY ??column DESC
{ column: 'industry' }
```

I get the following error though.
```
BadRequestException: ERROR: operator does not exist: ` character varying
Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

I found out this is because the escapeId escapes these identifiers as `column` and postgres does not support backticks. From postgres's website:

MySQL uses ` (accent mark or backtick) to quote system identifiers, which is decidedly non-standard.

Can the ID_GLOBAL_REGEXP constant be configurable?

**Comment by dougwilson** [comment]
Supporting dialects other than MySQL is outside the scope of this module.
