### ISSUE TITLE
Clarify support for passing a string to the second argument of format

### ISSUE THREAD

**Issue by lgarczyn** [mysqljs/sqlstring#54]
Currently the calls `format('?', 'test')` and `format('?', ['test'])` appear to give the exact same result, however neither `@types/sqlstring` nor `@types/mysql` mention this feature.

Is it deprecated, unintended or simply undocumented?

**Comment by dougwilson** [comment]
Hi @lgarczyn , it is a deprecated way to pass just a single value, yes. It used to be in the docs, but I believe it was removed in order to discourage it's usage, as it was confusing on how it worked, especially when that single `?` was itself an array.

**Comment by lgarczyn** [comment]
Thanks, that makes a whole lot of sense.
