### ISSUE TITLE
No idea to escape single quote' and double quote".

### ISSUE THREAD

**Issue by kmvan** [mysqljs/sqlstring#56]
```js
const sql = sqlstring.format('SELECT * FROM `terms` WHERE `name` = ?', [
    `single'double"`,
  ])
console.log(sql)
// output: SELECT * FROM `terms` WHERE `name` = 'single\'double\"'
// near "double": syntax error
```

Looks like `single\'double\"` shoud be `single''double""`
Need I create a user function to replace the quote?

**Comment by dougwilson** [comment]
Hi @kmvan sorry you are having trouble.  These methods of escaping values only works when the NO_BACKSLASH_ESCAPES SQL mode is disabled (which is the default state for MySQL servers).
