### ISSUE TITLE
How to use a literal `?` in a formatted query?

### ISSUE THREAD

**Issue by JonathanHolvey** [mysqljs/sqlstring#63]
If I use the `format` function on a query that contains a literal `?` this gets replaced, as per the documentation. How can I escape the `?` character so it doesn't get replaced?

```javascript
const { format }  = require('sqlstring')

format(`select * from mytable where foo = 'https://example.com?a=b' and bar = ?`, ['xyz'])
```
The resulting output from this would be 
```sql
select * from mytable where foo = 'https://example.com'xyz'a=b' and bar = ?
```
whereas I want
```sql
select * from mytable where foo = 'https://example.com?a=b' and bar = 'xyz'
```

**Comment by dougwilson** [comment]
You need to just put it as an argument. The ? Syntax is a copy from mysql placeholder syntax, which also has no way to escape it. Example:
```js
const { format }  = require('sqlstring')

format(`select * from mytable where foo = ? and bar = ?`, ['https://example.com?a=b', 'xyz'])
```
