### ISSUE TITLE
format sql with dynamic limit (LIMIT ?, ?)

### ISSUE THREAD

**Issue by phpmydev** [mysqljs/sqlstring#64]
as the title suggests, how to format ? so it is a number (no quotes)

**Comment by dougwilson** [comment]
You need to pass in the number as a number and not as strings. Example:
```js
console.log(SqlString.format('LIMIT ?, ?', [1, 20]))
```

There would only be quotes around the values if you use strings instead of numbers. I hope this helps.

**Comment by phpmydev** [comment]
immensely - thanks!
