### ISSUE TITLE
If the search word includes `%`...

### ISSUE THREAD

**Issue by kmvan** [mysqljs/sqlstring#65]
```js
const { format, escape } = require('sqlstring')
const searchWord = 'word%' // Only want to search end of like "abcword%".
const sql = format(
  `
SELECT * FROM ?? WHERE ?? LIKE ?
`,
  ['table', 'content', `%${escape(searchWord)}`]
)
console.log(sql)
// SELECT * FROM `table` WHERE `content` LIKE '%\'word%\''
```

### Expected output

`// SELECT * FROM `table` WHERE `content` LIKE '%word\%'
`
### Actual output

`// SELECT * FROM `table` WHERE `content` LIKE '%\'word%\''
`

Any idea?

**Comment by dougwilson** [comment]
Escape function only escapes a value into a sql value. You need to escape the various characters used in LIKE if you don't want them to be special just like with REGEXP.

**Comment by kmvan** [comment]
If the search word includes `?` question mark...

**Comment by dougwilson** [comment]
I'm not sure what your comment means. The LIKE statement does not assign any special meaning to a question mark, only percent signs and underscores.
