### ISSUE TITLE
Escaping date sometimes results in empty string

### ISSUE THREAD

**Issue by williamd5** [mysqljs/sqlstring#67]
This is a very weird issue that I was not able to fully debug to find the cause.

Part of my project's code looks like this:
```js
const mysql = require("mysql");
const db = mysql.createConnection(...);
```
When I run a query with {Date} objects, some of them resulted in a query like (demo)
![image](https://user-images.githubusercontent.com/66572326/156400561-1126da34-0564-4b5d-b136-da55213d7b90.png)
![image](https://user-images.githubusercontent.com/66572326/156400588-940189ce-c4df-47bb-af5d-b6de52039d19.png)
Running
`mysql.escape(new Date())` I get empty string.

I installed mysql and sqlstring on a new plain project and could not reproduce this. `mysql.escape(...)` seems to work with any other type.

Any ideas what could be the cause for this?

![image](https://user-images.githubusercontent.com/66572326/156402367-1c9005b4-43dd-4609-82e5-fdb20744c8a1.png)

**Comment by dougwilson** [comment]
I'm going to mark this as a bug for now, as it should work for `Date` objects from different isolates, which it doesn't today. Of course, if that is your issue or not, I can't say for sure. If you are able to step through the buggy instance with a debugger, you can check if `instanceof Date` returns `false` for the object or not.

**Comment by williamd5** [comment]
Thank you for the information. I will try to debug as you said and see if I can find anything.

**Comment by williamd5** [comment]
In sqlstring lib I added debug to check `val instanceof Date` and it outputs false. According to [this SO answer](https://stackoverflow.com/a/643827/7089726)

> you can use the instanceof operator, i.e. But it will return true for invalid dates too, e.g. new Date('random_string') is also instance of Date
> ```js
> date instanceof Date
> ```
> **This will fail if objects are passed across frame boundaries.**
> 
> A work-around for this is to check the object's class via
> ```js
> Object.prototype.toString.call(date) === '[object Date]'
> ```
Here is what I debugged:
![image](https://user-images.githubusercontent.com/66572326/156423689-5aade0a5-57d4-4430-ab46-78c2d12f3fa8.png)
![image](https://user-images.githubusercontent.com/66572326/156423971-9ea014cb-9287-4e6d-ae2a-f0365a33c558.png)

The recommended alternative in the SO answer seems to work. I will open a PR on sqlstring with a reference to this issue.
![image](https://user-images.githubusercontent.com/66572326/156424617-194aae8b-c54d-47f4-b733-d58d73a55283.png)

**Comment by williamd5** [comment]
If you could make the fix that would be great

**Comment by williamd5** [comment]
Any suggestion how to test cross-frame in the tests? I have started a branch on a fork [cloudnode-pro/sqlstring@patch/67](https://github.com/cloudnode-pro/sqlstring/tree/patch/%2367)

**Comment by dougwilson** [comment]
Hi @williamd5 sorry I was away over the week; I just have a short amount of time today, so wanted to get this fixed for ya. I landed the change + test.
