### ISSUE TITLE
comma separated when object has more than one key in where clause, it should be 'and' separated

### ISSUE THREAD

**Issue by aminabedi** [mysqljs/sqlstring#7]
in line 166:
sql += (sql.length === 0 ? '' : ', ') + SqlString.escapeId(key) + ' = ' + SqlString.escape(val, true, timeZone);
should be:
sql += (sql.length === 0 ? '' : 'and ') + SqlString.escapeId(key) + ' = ' + SqlString.escape(val, true, timeZone);

**Comment by dougwilson** [comment]
Hi! It sounds like you are using the object incorrectly; this module does not support any type of WHERE formatting. This module is mainly a simple mode for the bare minimum. There are some really full-featured modules you can use to dynamically construct WHERE clauses :)
